version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --timeout 60
        --workers 2
        --threads 4
        "app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_DEBUG: '0'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'

  celery_1:
    build: .
    command: celery -A app.celery worker --loglevel=info -f logs/celery_1.log
    environment:
      FLASK_DEBUG: '0'
    volumes:
      - '.:/app'

  celery_2:
    build: .
    command: celery beat -A app.celery --schedule=/tmp/celerybeat-schedule --loglevel=INFO --pidfile=/tmp/celerybeat.pid -f logs/celery_2.log
    environment:
      FLASK_DEBUG: '0'
    volumes:
      - '.:/app'

volumes:
  redis:
