version: '2'

services:
  redis:
      image: 'redis:3.0-alpine'
      command: redis-server --requirepass 1234567a@@
      volumes:
        - 'redis:/data'
      ports:
        - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5002
        --access-logfile -
        --timeout 60
        --workers 2
        --threads 4
        "app.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_DEBUG: '0'
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'

  celery:
    build: .
    command: celery -A app.celery.celery worker --loglevel=info -f logs/celery.log
    environment:
      FLASK_DEBUG: '0'
    volumes:
      - '.:/app'

volumes:
  redis:
